### ISSUE TITLE
Scoped Query - Sql sintaxe erro

### ISSUE THREAD

**Issue by FactorySolution** [HashLoad/ORMBr#10]
Ao utilizar o scoped Query com Order by, por exemplo, a estrutura do sql fica errada:

`SELECT PESSOA.ID, PESSOA.NOME FROM PESSOA
ORDER BY PESSOA.ID
WHERE PESSOA.NOME = 'ANDRE'`

Correto:

`SELECT PESSOA.ID, PESSOA.NOME FROM PESSOA
WHERE PESSOA.NOME = 'ANDRE'
ORDER BY PESSOA.ID`

Solução para MySql:

function TDMLGeneratorMySQL.GeneratorSelectWhere(AClass: TClass; AWhere: string;
  AOrderBy: string; APageSize: Integer): string;
var
  LCriteria: ICriteria;
  LScopeWhere: String;
  LScopeOrderBy: String;
begin
  // Pesquisa se já existe o SQL padrão no cache, não tendo que montar toda vez
//  if not TQueryCache.Get.TryGetValue(AClass.ClassName, Result) then
//  begin
    LCriteria := GetCriteriaSelect(AClass, -1);
    Result := LCriteria.AsString;
    // Faz cache do comando padrão
//    TQueryCache.Get.AddOrSetValue(AClass.ClassName, Result);
//  end;
  // Scope
  LScopeWhere := GetGeneratorQueryScopeWhere(AClass);
  if LScopeWhere <> '' then
    LScopeWhere := ' WHERE ' + LScopeWhere;

  LScopeOrderBy := GetGeneratorQueryScopeOrderBy(AClass);
  if LScopeOrderBy <> '' then
    LScopeOrderBy := ' ORDER BY ' + LScopeOrderBy;

  // Params Where and OrderBy
  if (Length(AWhere) > 0) or (Length(LScopeWhere) > 0) then
  begin
    if LScopeWhere <> '' then
    begin
      Result := Result + LScopeWhere;
    end;
    if AWhere <> '' then
    begin
      Result := Result + IfThen(Pos('WHERE', Result) > 0, ' AND ', ' WHERE ');
      Result := Result + AWhere;
    end;
  end;

  if (Length(AOrderBy) > 0) or (Length(LScopeOrderBy) > 0) then
  begin
    if LScopeOrderBy <> '' then
    begin
      Result := Result + LScopeOrderBy;
    end;
    if AOrderBy <> '' then
    begin
      Result := Result + IfThen(Pos('ORDER BY', Result) > 0, ', ', ' ORDER BY ');
      Result := Result + AOrderBy;
    end;
  end;

  // Monta SQL para paginação
  if APageSize > -1 then
    Result := Result + GetGeneratorSelect(LCriteria);
end;

**Comment by isaquepinheiro** [comment]
> // Pesquisa se já existe o SQL padrão no cache, não tendo que montar toda vez
> // if not TQueryCache.Get.TryGetValue(AClass.ClassName, Result) then
> // begin
> LCriteria := GetCriteriaSelect(AClass, -1);
> Result := LCriteria.AsString;
> // Faz cache do comando padrão
> // TQueryCache.Get.AddOrSetValue(AClass.ClassName, Result);
> // end;
> // Scope

Esse recurso é para performance, mais realmente em alguns bancos a ordem de gerar cousa o problema o interessante é como esta no paga, tentar arrumar o Cache traz parformance para não ter que ficar usando Rtti a toda chamada, alguns banco funciona bem.

**Comment by isaquepinheiro** [comment]
> if LScopeOrderBy <> '' then
> begin
> Result := Result + LScopeOrderBy;
> end;
> if AOrderBy <> '' then
> begin
> Result := Result + IfThen(Pos('ORDER BY', Result) > 0, ', ', ' ORDER BY ');
> Result := Result + AOrderBy;
> end;

Colaboração aplicada no fonte oficial.
