### ISSUE TITLE
corrige-json-invalido

### ISSUE THREAD

**Issue by basster26** [HashLoad/ORMBr#11]
Ao usar o TORMBrJson.ObjectListToJsonString o meu json estava ficando invalido.
![image](https://github.com/HashLoad/ORMBr/assets/81237435/d2bdd6fd-5b71-4c21-afa8-9d9dbc77cc6a)

**Comment by isaquepinheiro** [comment]
Confere por favor na Master ou Develop, acho que já subi essa correção.

**Comment by basster26** [comment]
Eu tentei commitar só que esta dando sem permissão, eu puxei o ramo de dev ja esta corrigido, no master ainda nao está.
