### ISSUE TITLE
Criação de tabelas no DB a partir de "ormbr.model.client;"

### ISSUE THREAD

**Issue by gaitolini** [HashLoad/ORMBr#13]
Comecei a utilizar ORMBr para meus projetos como estudo do Framework, porém estou com dificuldade em criar tabelas novas no banco de dados.

Estou utilizando o MYSQL na versão 57, pois estou com uma versão da IDE Delphi x86. Para caso de estudo criei um schema chamado "ormbr" sem nenhuma tabela em meu mySQL, porém não consigo criar uma tebela no banco a partir da model de exemplo: ormbr.model.client;

modifiquei o atribuição de metadados [Entity] para: [Entity('client', 'ormbr')]

mesmo assim após abri o banco o sistema diz que a tabela não existe.

basicamente estou utilizando o projeto de exemplo FIREDAC  Crud simples, e instalei as dependências com o BOSS.

**Comment by isaquepinheiro** [comment]
Olá, existe um exemplo na pasta ..\ORMBr\Examples\Metadata\FireDAC, altere ele para acessar o seu banco MySQL, crie seu modelo com base no que lá existe, e execute para vê.
No exemplo tem como visualizar antes o script que foi criado, copie e cole ele em uma ferramenta, analise e dai, terá uma noção o que pode estar acontecendo, encontrando erro no script, depure e vê se acha a que esteja gerando errado, se tiver, cada banco tem seus fontes separados, é bem simples descobrir onde possa estar sendo gerado algo errado.

**Comment by gaitolini** [comment]
Olá 👍 
Obrigado @isaquepinheiro. 
Farei os teste com o exemplo do Metadata no MySQL.

Saudações
