### ISSUE TITLE
"Undeclared identifier: IsHidden"

### ISSUE THREAD

**Issue by wellintonmbvix** [HashLoad/ORMBr#25]
Como podem ver na imagem abaixo a propriedade "IsHidden" não está sendo reconhecida no arquivo ormbr.bind.pas nesse último release 1.1.8

![Captura de tela 2024-10-22 160631](https://github.com/user-attachments/assets/0fdc763b-bdb6-4537-98f1-56df23cd7e88)

**Comment by isaquepinheiro** [comment]
> Como podem ver na imagem abaixo a propriedade "IsHidden" não está sendo reconhecida no arquivo ormbr.bind.pas nesse último release 1.1.8
> 
> ![Captura de tela 2024-10-22 160631](https://private-user-images.githubusercontent.com/50427422/378999595-0fdc763b-bdb6-4537-98f1-56df23cd7e88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MjgwNTcsIm5iZiI6MTcyOTYyNzc1NywicGF0aCI6Ii81MDQyNzQyMi8zNzg5OTk1OTUtMGZkYzc2M2ItYmRiNi00NTM3LTk4ZjEtNTZkZjIzY2Q3ZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDIwMDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOTk0MWYxZWUyZWQ3YzIxNzMyYjNmYjVhZDRiNDY4ZDhkYjQ0MDUxZDVlY2RjMWNiNDliYTJjZWM2NDI5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5fmaU9oH6D1szy8CFxA7aAj5aPsV246wZrMeOre1V90)

Atualize as dependências
