### ISSUE TITLE
Problemas com campos tipo Nullable<T>

### ISSUE THREAD

**Issue by ademarrs** [HashLoad/ORMBr#5]
Quando é solicitado para gera um JSON de um objeto propriedades do tipo Nullable<T>, dá erro. O valor da propriedade está retornando como um array com dois elementos Ex.:  "fOR_DIG": [  "9",   "@"  ] .

<img width="684" alt="codigo" src="https://user-images.githubusercontent.com/29805902/198283270-e5d1ad34-d76d-4e19-94a7-aa1e90eba308.png">

**Comment by ademarrs** [comment]
Alguém tem alguma sugestão de como corrigir o problema?

**Comment by isaquepinheiro** [comment]
Faça o teste no exemplo ..\ORMBr\Examples\JSON até onde sei, não existe problema desse tipo reportado, baixe os fontes da branche Develop, caso não tenha baixado de lá, para teste tb
