### ISSUE TITLE
Erro de paginação com FireBird

### ISSUE THREAD

**Issue by ademarrs** [HashLoad/ORMBr#6]
Ao usar a paginação com o banco de dados FireBird ocorre um erro quando é usado o Find, a sentença SQL não é preenchida corretamente quando tem paginação (% SKIP %) .

<img width="771" alt="OrmBrErro" src="https://user-images.githubusercontent.com/29805902/202797251-a549a2c2-214d-4fa0-98cd-fb761d37f8cb.png">

**Comment by isaquepinheiro** [comment]
Qual o motivo de usar um Find, depois querer usar um FindID ? Se entendi direito e estiver usando assim, o erro não está no ORMBr, mas na forma de usar.
Não vejo necessidade nisso, mesmo porque se tiver um IContainer e usar FindID, virá somente um registro e não terá mais para paginar.
Quando usar paginação, use o Find, somente UMA VEZ, e o ClientDataSet ou  FDMenTabel irá fazer automaticamente a paginação para vc, até o final dos registro.
Se precisar trazer somente um registro, crie outro IContainer para ele, e ai faça nele o FindID, nele e não no IContainer que usou para paginação

**Comment by isaquepinheiro** [comment]
Imagine o seguinte:
Você tem uma tela que mostra um Grid, e nesse grid poderá ser listado todos os registro paginando. Dai quando vc pressiona uma tecla, vc quer ir para outra tela, que mostra os dados em detalhe, onde pode ser alterado, visualizado, etc...
Veja, vc tem duas telas:
1a para pesquisa (Essa tela por questão primeiro e principal, de boas práticas, e depois por espaço, vc deve fazer um select no no banco trazendo somente o que será mostrado nela.
2a para Editar, Visualizar, Incluir, aqui novamente usando boas práticas, deve ter outro dataset, exclusivo para esse recurso, e não usar o mesmo dataset de pesquisa, e nele deve ser executado um Select filtrando somente o ID do registro selecionado no dataset, que foi usado na tela de pesquisa, essas boas práticas não é uma exigência do ORMBr, elas devem ser usadas, mesmo se não usasse o ORMBr e fizesse isso nativo, com datasets do Delphi.
Então a mesmas boas práticas, devem ser usadas com o ORMBr, criando um IContainer para cada recurso, 1 para pesquisa e outro para Editar, Visualizar ou Incluir.
A diff, usando o ORMBr é que vc deve criar duas classes, uma para a tela de pesquisa, usando somente os campos que precisar nela, e aconselho a criar uma VIEW no banco tb, para que a classe represente a essa view. Outra class, dai sim, completa, que servirá para Editar, Visualizar ou Incluir um novo registro.

**Comment by isaquepinheiro** [comment]
No curso mostro exatamente como fazer isso, na tela de nota fiscal

**Comment by ademarrs** [comment]
Olá,

**Comment by isaquepinheiro** [comment]
Fiz o teste aqui, e está funcionando perfeitamente usando Firebird com component FDMenTable, os fontes são da branche Develop, segue print mostrando
![image](https://user-images.githubusercontent.com/4005289/203057887-37b2560c-bf90-47ec-a52d-007090986ccd.png)
![image](https://user-images.githubusercontent.com/4005289/203058052-ddfbad78-5a08-401c-bd2f-c8650608b0fa.png)

**Comment by isaquepinheiro** [comment]
Fiz ajustes e testei o exemplo da pasta ORMBr\Examples\Data\Uso TManagerDataSet

**Comment by isaquepinheiro** [comment]
Um detalhe a ser observado, a Paginação deve ser usada desde o 1o Find(), a escrita SQL não deve ser iniciada sem paginação e depois querer adicionar paginação, veja se não pode ser isso, com mostrado acima, está tudo funcionando.

**Comment by ademarrs** [comment]
Baixamos o exemplo que vc fez o teste, mas dá erro de compilação, faltam algumas units.
<img width="598" alt="TreeDevelop" src="https://user-images.githubusercontent.com/29805902/203071631-0a3695bf-a8f2-4f2d-957e-938216c7c7a2.png">
