### ISSUE TITLE
bug com chaves primarias do tipo TGUID

### ISSUE THREAD

**Issue by wesleybobato** [HashLoad/ORMBr#7]
Olá Isaque boa noite, tudo bem?

Estou reportando um BUG com o uso de chaves primárias do tipo TGUID, todos detalhes estão nos links abaixo, obrigado!

Aqui tem um vídeo demonstrando o problema
https://vimeo.com/784447972/7ffba3ba41

Aqui o código fonte da demonstração
https://www.mediafire.com/file/uapuzmupmm1vl0y/ORMBr.zip/file

**Comment by CarlosHe** [comment]
Acredito eu que isso não seja um erro do ORMBr com relação a chave primária do tipo GUID com auto increment. O SQLite não tem suporte nativo para o auto increment em colunas do tipo GUID.

O que pode ser feito é criar uma trigger para gerar o valor da chave primária no formato GUID.

**Comment by isaquepinheiro** [comment]
respondido
